"""fix enums & training models

Revision ID: c8fda3470f49
Revises: 7a98b7f8d9e0
Create Date: 2025-11-09 21:06:13.102394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fda3470f49'
down_revision: Union[str, Sequence[str], None] = '7a98b7f8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.create_index('ix_training_org', ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainings_title'), ['title'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', name='enrollment_status_enum'), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'training_id', name='uq_enrollment_user_training')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_enrollment_training', ['training_id'], unique=False)
        batch_op.create_index('ix_enrollment_user', ['user_id'], unique=False)

    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_url', sa.String(length=1000), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_id', 'order_index', name='uq_module_training_order')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index('ix_module_training', ['training_id'], unique=False)

    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='progress_status_enum'), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_progress_user_module')
    )
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index('ix_progress_module', ['module_id'], unique=False)
        batch_op.create_index('ix_progress_user', ['user_id'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_company_org_name', ['org_id', 'name'])

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'EMPLOYEE', name='role_enum'),
               existing_nullable=False)
        batch_op.create_index('ix_membership_org', ['org_id'], unique=False)
        batch_op.create_index('ix_membership_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_membership_user')
        batch_op.drop_index('ix_membership_org')
        batch_op.alter_column('role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'EMPLOYEE', name='role_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_company_org_name', type_='unique')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_user')
        batch_op.drop_index('ix_progress_module')

    op.drop_table('progress')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index('ix_module_training')

    op.drop_table('modules')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollment_user')
        batch_op.drop_index('ix_enrollment_training')

    op.drop_table('enrollments')
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainings_title'))
        batch_op.drop_index('ix_training_org')

    op.drop_table('trainings')
    # ### end Alembic commands ###
